version: "3.9"

services:
  server:
    container_name: task
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MONGODB_URL: mongodb+srv://shareb_Admin:d5KpJeuyNTtYM4D1@shareb.5wqep8o.mongodb.net/sharebDBTest
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped
